//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceSys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-08-28")]
        public global::System.DateTime LastStartDate {
            get {
                return ((global::System.DateTime)(this["LastStartDate"]));
            }
            set {
                this["LastStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-08-28")]
        public global::System.DateTime LastEndDate {
            get {
                return ((global::System.DateTime)(this["LastEndDate"]));
            }
            set {
                this["LastEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-08-28")]
        public global::System.DateTime LastChangeDate {
            get {
                return ((global::System.DateTime)(this["LastChangeDate"]));
            }
            set {
                this["LastChangeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastHour {
            get {
                return ((string)(this["LastHour"]));
            }
            set {
                this["LastHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMinutes {
            get {
                return ((string)(this["LastMinutes"]));
            }
            set {
                this["LastMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastConference {
            get {
                return ((string)(this["LastConference"]));
            }
            set {
                this["LastConference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastHall {
            get {
                return ((string)(this["LastHall"]));
            }
            set {
                this["LastHall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-08-28")]
        public global::System.DateTime ArrivalsLastChangeDate {
            get {
                return ((global::System.DateTime)(this["ArrivalsLastChangeDate"]));
            }
            set {
                this["ArrivalsLastChangeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArrivalsLastHour {
            get {
                return ((string)(this["ArrivalsLastHour"]));
            }
            set {
                this["ArrivalsLastHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArrivalsLastMin {
            get {
                return ((string)(this["ArrivalsLastMin"]));
            }
            set {
                this["ArrivalsLastMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-08-28")]
        public global::System.DateTime RegLastChange {
            get {
                return ((global::System.DateTime)(this["RegLastChange"]));
            }
            set {
                this["RegLastChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegLastHour {
            get {
                return ((string)(this["RegLastHour"]));
            }
            set {
                this["RegLastHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegLastMin {
            get {
                return ((string)(this["RegLastMin"]));
            }
            set {
                this["RegLastMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LetterTemplateDirectory {
            get {
                return ((string)(this["LetterTemplateDirectory"]));
            }
            set {
                this["LetterTemplateDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LetterOutputDirectory {
            get {
                return ((string)(this["LetterOutputDirectory"]));
            }
            set {
                this["LetterOutputDirectory"] = value;
            }
        }
    }
}
